version: '3'
services:
  catalogue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: "catalogue"
      POSTGRES_USER: "catalogue"
      POSTGRES_PASSWORD: "catalogue_password"
    ports:
      - "5432:5432"

volumes:
  db_data: