version: '3'
services:
  catalogue:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  testday-api:
    image: heurekaoc/testday-api:latest
    ports:
      - "5000:5000"
